### ISSUE TITLE
Form Customization: Standard fields are ignored

### ISSUE THREAD

**Issue by 4ntz** [goldsky/Lingua#33]
I have set up some Form Customization rules which include hiding / renaming some of the standard fields (description, introtext, link-attributes). Everything is fine on my standard language but when I switch to another language, all of the standard fields appear AND my custom renaming is gone. 
One mor thing: when I rename a standard field, the flag is gone.

![lingua_form_customization_issue](https://cloud.githubusercontent.com/assets/1968479/5745794/924adcd4-9c2b-11e4-8a05-df236aa01003.jpg)

**Comment by goldsky** [comment]
After trying to hack around, I found that this an exception for Lingua to work with.

The Form Customization is loaded by a [controller](https://github.com/modxcms/revolution/blob/master/core/model/modx/modactiondom.class.php), that is called by [manager's controller](https://github.com/modxcms/revolution/blob/master/core/model/modx/modmanagercontroller.class.php#L137) around line 137 and rendered around line 159.
What makes the problem is that [resource's controler class](https://github.com/modxcms/revolution/blob/master/manager/controllers/default/resource/resource.class.php) does't not override `firePostRenderEvents()` which is called by manager's controller around line 186.

What makes it harder is that while the JavaScript script in HTML block has been called in `$this->registerCssJs();` on line 163, the manager's controller doesn't have `addLastHtml()` to place HTML block in the last part of HTML's body.

That said, Lingua doesn't work well with Form Customization.

**Comment by goldsky** [comment]
May be this explains it better.

![untitled](https://cloud.githubusercontent.com/assets/308524/5981656/acea92bc-a8ee-11e4-8ccf-71f236e01f6a.png)

**Comment by goldsky** [comment]
I found a temporary solution, although this is not ideal.
I use Javascript to recheck back the rendered page to get the visibility state.

![fc](https://cloud.githubusercontent.com/assets/308524/5992700/8dd61f94-aa66-11e4-854a-61bb9800313f.png)

That means, Lingua is only able to get the "rules" from the rendered fields, to check whether they are hidden or not.
In the mean time, I'll try to discuss the possibility with MODX core team to add a plugin hook in Form Customization's class, so Lingua can get the rules directly from the database.

**Comment by smashstack-kris** [comment]
@goldsky not sure if this is the right place to post this (if not, please feel free to delete my comment here), but we're trying to work on form customization based on language assigned to a MODX manager.  The goal is to limit via form customization (or is there a better approach) to keep a translator out of the other languages on the site that other managers are working on.  I just posted this ticket here in the forums:

https://forums.modx.com/thread/100634/lingua-plugin-is-it-possible-to-define-form-customization-by-language

Be curious as to whether you have any suggestions to accomplish what we're trying to do.

Thanks! (and awesome plugin btw)

**Comment by 4ntz** [comment]
@goldsky the system setting is getting ignored, when the resource is a collection. On language switch in the manager ALL fields disappear (pagetitle, longtitle, etc.).
